create table if not exists song_likes (
  id bigint generated by default as identity primary key,
  track_id integer not null,
  stage text not null check (stage in ('round16', 'top8')),
  user_key text not null,
  created_at timestamptz not null default now(),
  unique (track_id, stage, user_key)
);

create table if not exists song_comments (
  id bigint generated by default as identity primary key,
  track_id integer not null,
  stage text not null check (stage in ('round16', 'top8')),
  parent_comment_id bigint references song_comments(id) on delete cascade,
  difficulty text check (difficulty is null or difficulty in ('EZ', 'HD', 'IN', 'AT')),
  nickname text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table song_comments
  add column if not exists parent_comment_id bigint references song_comments(id) on delete cascade;

create index if not exists song_likes_stage_track_idx
  on song_likes(stage, track_id);

create index if not exists song_comments_stage_track_created_idx
  on song_comments(stage, track_id, created_at desc);

create index if not exists song_comments_parent_idx
  on song_comments(parent_comment_id);

alter table song_likes enable row level security;
alter table song_comments enable row level security;

drop policy if exists "song_likes_select_public" on song_likes;
drop policy if exists "song_likes_insert_public" on song_likes;
drop policy if exists "song_comments_select_public" on song_comments;
drop policy if exists "song_comments_insert_public" on song_comments;

create policy "song_likes_select_public"
on song_likes
for select
to anon, authenticated
using (true);

create policy "song_likes_insert_public"
on song_likes
for insert
to anon, authenticated
with check (
  stage in ('round16', 'top8')
  and length(user_key) between 12 and 96
);

create policy "song_comments_select_public"
on song_comments
for select
to anon, authenticated
using (true);

create policy "song_comments_insert_public"
on song_comments
for insert
to anon, authenticated
with check (
  stage in ('round16', 'top8')
  and nickname <> ''
  and content <> ''
  and (difficulty is null or difficulty in ('EZ', 'HD', 'IN', 'AT'))
);
